/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : TEMP1.h
**     Project     : test2
**     Processor   : MCF51QE128CLK
**     Component   : LM61B
**     Version     : Component 01.030, Driver 01.00, CPU db: 3.00.078
**     Compiler    : CodeWarrior ColdFireV1 C Compiler
**     Date/Time   : 2015-07-29, 17:26, # CodeGen: 1
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         Measure         - void TEMP1_Measure(void);
**         ReadTemperature - signed char TEMP1_ReadTemperature(void);
**
**     (c) Copyright Erich Styger, 2008
**     http      : www.hslu.ch
**     mail      : erich.styger@hslu.ch
** ###################################################################*/
/*!
** @file TEMP1.h
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup TEMP1_module TEMP1 module documentation
**  @{
*/         

#ifndef __TEMP1_H
#define __TEMP1_H

/* MODULE TEMP1. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "Vcc1.h"
#include "AD1.h"

#include "Cpu.h"




void TEMP1_Measure(void);
/*
** ===================================================================
**     Method      :  TEMP1_Measure (component LM61B)
**     Description :
**         Starts the measuring process for the sensor value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

signed char TEMP1_ReadTemperature(void);
/*
** ===================================================================
**     Method      :  TEMP1_ReadTemperature (component LM61B)
**     Description :
**         Reads the temperature from the sensor.
**     Parameters  : None
**     Returns     :
**         ---             - Temperature value in the range of -25..85
**                           Degree Celsius
** ===================================================================
*/

/* END TEMP1. */

#endif
/* ifndef __TEMP1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale ColdFireV1 series of microcontrollers.
**
** ###################################################################
*/
