/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : TEMP1.c
**     Project     : test2
**     Processor   : MCF51QE128CLK
**     Component   : LM61B
**     Version     : Component 01.030, Driver 01.00, CPU db: 3.00.078
**     Compiler    : CodeWarrior ColdFireV1 C Compiler
**     Date/Time   : 2015-07-29, 17:26, # CodeGen: 1
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         Measure         - void TEMP1_Measure(void);
**         ReadTemperature - signed char TEMP1_ReadTemperature(void);
**
**     (c) Copyright Erich Styger, 2008
**     http      : www.hslu.ch
**     mail      : erich.styger@hslu.ch
** ###################################################################*/
/*!
** @file TEMP1.c
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup TEMP1_module TEMP1 module documentation
**  @{
*/         

/* MODULE TEMP1. */

#include "TEMP1.h"

/*
** ===================================================================
**     Method      :  TEMP1_Measure (component LM61B)
**     Description :
**         Starts the measuring process for the sensor value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void TEMP1_Measure(void)
{
  (void)AD1_MeasureChan(TRUE, 0);
}

/*
** ===================================================================
**     Method      :  TEMP1_ReadTemperature (component LM61B)
**     Description :
**         Reads the temperature from the sensor.
**     Parameters  : None
**     Returns     :
**         ---             - Temperature value in the range of -25..85
**                           Degree Celsius
** ===================================================================
*/
signed char TEMP1_ReadTemperature(void)
{
  #define TemperatureCompensation_c    -5 /* number of degrees in Celsius to add/subtract to compensate for self heating etc. */
  #define TempSensormilliVoltOffset_c 600 /* LM61B ZERO degrees Celsius offset in milliVolt */
  #define milliVoltPerDegree_c         10 /* LM61B milliVolt per 1 degree Celsius */
  word milliVolts;
  word adcValue;

  (void)AD1_GetChanValue16(0, &adcValue);
  adcValue >>= 6; /* right justified value */
  milliVolts = (word)(adcValue*3); /* Convert milliVolts to Celsius */
  return(signed char)((int8_t)((milliVolts - TempSensormilliVoltOffset_c)/milliVoltPerDegree_c) + TemperatureCompensation_c);
}

/* END TEMP1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale ColdFireV1 series of microcontrollers.
**
** ###################################################################
*/
